CLASS zds_class01 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zds_class01 IMPLEMENTATION.
METHOD if_oo_adt_classrun~main.
out->write('Hello world').
ENDMETHOD.
ENDCLASS.
